name = "maya-calendar-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
# LINE_CHANNEL_SECRET = "" # Set via `wrangler secret put`
# LINE_CHANNEL_ACCESS_TOKEN = ""
# LARK_APP_ID = ""
# LARK_APP_SECRET = ""
# LARK_BASE_APP_TOKEN = ""
# LARK_BASE_TABLE_ID = ""
